# Generated by Django 4.2.27 on 2026-01-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.CharField(default='Main Examination Center, Block A', max_length=255),
        ),
    ]
