# Generated by Django 4.2.27 on 2026-01-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_registration_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='hold_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
